# Site settings
title: Remote Raise is a pitching event connecting the investment community with startup founders.
shortTitle: Remote Raise
email: info@raise-ventures.com
author: David Shawe
description: Remote Raise is a pitching event connecting the investment community with startup founders.
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
